Update IaC workflow to show cancellation and error in sticky comment

diff --git a/.github/workflows/uat_iac.yml b/.github/workflows/uat_iac.yml
--- a/.github/workflows/uat_iac.yml
+++ b/.github/workflows/uat_iac.yml
@@ -41,6 +41,9 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+      - name: Simulate error
+        run: exit 1
+
       - name: Delete resource group if it exists
         if: success()
         run: |
@@ -66,10 +69,36 @@ jobs:
             spinup
 
       - name: Get current datetime to write in PR comment
+        if: always()
         run: |
           echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV
 
+      - name: Update PR comment to indicate failure
+        if: failure()
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          header: uat
+          message: |
+            # UAT Environment - _Spin up failed!_
+
+            Spin up failed on ${{ env.current_time }}
+
+            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.
+
+      - name: Update PR comment to indicate cancellation
+        if: cancelled()
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          header: uat
+          message: |
+            # UAT Environment - _Spin up cancelled!_
+
+            Spin up cancelled on ${{ env.current_time }}
+
+            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.
+
       - name: Update PR Comment
+        if: success()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: uat
@@ -77,6 +106,8 @@ jobs:
             # UAT Environment - _Created_
 
             UAT environment created on ${{ env.current_time }}
+
+            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.
 
   teardown-uat:
     permissions:
@@ -102,6 +133,9 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+      - name: Simulate error
+        run: exit 1
+
       - name: Delete resource group if it exists
         if: success()
         run: |
@@ -110,7 +144,7 @@ jobs:
           az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --yes
           fi
 
-      - name: Remove CD label from PR
+      - name: Remove teardown label from PR
         if: always()
         uses: actions-ecosystem/action-remove-labels@v1
         with:
@@ -118,10 +152,36 @@ jobs:
             teardown
 
       - name: Get current datetime to write in PR comment
+        if: always()
         run: |
           echo "current_time=$(date +'%d %b **%H:%M** %Z')" >> $GITHUB_ENV
 
-      - name: Update PR Comment
+      - name: Update PR comment to indicate failure
+        if: failure()
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          header: uat
+          message: |
+            # UAT Environment - _Teardown failed!_
+
+            Teardown failed on ${{ env.current_time }}
+
+            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.
+
+      - name: Update PR comment to indicate cancellation
+        if: cancelled()
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          header: uat
+          message: |
+            # UAT Environment - _Teardown cancelled!_
+
+            Teardown cancelled on ${{ env.current_time }}
+
+            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.
+
+      - name: Update PR Comment to indicate success
+        if: success()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: uat
@@ -129,6 +189,8 @@ jobs:
             # UAT Environment - _Torn down_
 
             UAT environment torn down on ${{ env.current_time }}
+
+            Workflow run logs are **[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**.
 
   validate-labels:
     permissions:
